BUTTON_WIDTH = 150
BUTTON_HEIGHT = 30

WINDOW_WIDTH = 900
WINDOW_HEIGHT = 450

TEXTAREA_WIDTH = (WINDOW_WIDTH - 20) / 2
TEXTAREA_HEIGHT = 150

TEXTINPUT_WIDTH = (WINDOW_WIDTH - 20) / 2
TEXTINPUT_HEIGHT = 30

LABEL_WIDTH = TEXTAREA_WIDTH
LABEL_HEIGHT = 30